### ISSUE TITLE
The Elektron Object API roadmap

### ISSUE THREAD

**Issue by DzmitryShylovich** [thomsonreuters/Elektron-SDK#10]
Hi, guys. According to [this](http://financial.thomsonreuters.com/content/dam/openweb/documents/pdf/financial/elektron-api-faqs.pdf) doc
```
The Elektron Object API: Under development now, this API provides developers with easy-to-use, open-source business objects using
the Thomson Reuters Domain Models (e.g. order books, yield curves, volatility surfaces, and other financial markets models.) This API is
expected to be in beta at the end of 2015 and will be enhanced by customers and Thomson Reuters based on customer feedback.
```

So is there any info when this api will be available here?

**Comment by IainScott** [comment]
Hi Dzmitry

There is an early version in the preview branch that you can take a look at now and we welcome any feedback.

At the moment, our priority is to get the Elektron Message API complete on the consumer and provider side so our focus is in that area.  We will continue limited development of the Object API in parallel with a formal release is likely to be 1st half of next year.

Thanks

Iain

**Comment by DzmitryShylovich** [comment]
Thank you.

What do you mean by saying?

> our priority is to get the Elektron Message API complete on the consumer and provider side

Is it just polishing or EMA is not production ready yet?

**Comment by IainScott** [comment]
Hi,

What it means is that there are elements of ema that are not released yet on the data provider side (I.e. Publishing) so we are working on those.

Both ema c++ and Java consumer Apis are fully production ready.  Those elements are in the main branch.

Thanks

Iain

**Comment by DzmitryShylovich** [comment]
Consumer is exactly what I need, thanks. It's really hard to choose the right api :smile:
