### ISSUE TITLE
EMA lacks method to obtain an Enum's display text.

### ISSUE THREAD

**Issue by steve-o** [thomsonreuters/Elektron-SDK#11]
ref:  https://community.developers.thomsonreuters.com/questions/6595/decoding-fieldlist-contents-with-field-and-enumera.html

ETA includes the following:

```
EnumType enumType = dictionary.entryEnumType(dictionaryEntry, fidEnumValue);
System.out.println (enumType.display().toString());
```

EMA only exposes access to the underlying value.

**Comment by andrzejczop** [comment]
The EMA is planning on adding the enum value to enum text conversion utility. Understandably such feature would greatly improve the EMA's ease of use experience. It is worthy to mention that the "open source nature" of the EMA allows code modifications and addition of new features. Pull requests with new features and or bug fixes are welcome.

**Comment by GregLee-TR** [comment]
We will track your request with EMA-559.   Thanks again for the feedback!
