### ISSUE TITLE
The explanation of EmaConfig.xml usage is not clear.

### ISSUE THREAD

**Issue by sdeber** [thomsonreuters/Elektron-SDK#12]
In the docs, there is no explanation about where to place EmaConfig.xm file on the file system and how an OmmConsumerConfig object can be constructed out of it. Could you please explain it in more details?

**Comment by seba5** [comment]
The EmaConfig.xml file needs to be located in the same location as the application. 
On the OmmConsumerConfig object you can call the consumerName() method that takes in the name of the consumer configuration from the EmaConfig.xml file. Please take a look at the Consumer 110 application. It shows how the application is using the EmaConfig.xml.
Please let us know if you have more questions, thank you.

**Comment by seba5** [comment]
A clarification was stated in the top level ReadMe_First.txt as well as the EMACPP_ConfigGuide.pdf.  Thanks for you feedback.
