### ISSUE TITLE
Separating Docs from Sources

### ISSUE THREAD

**Issue by menuet** [thomsonreuters/Elektron-SDK#14]
Hi,

The repository is very big: it took me 30 minutes to clone it.
Most of its contents are documentations. Would it be move them in a separate repository?
What do you think ?

**Comment by steve-o** [comment]
This is typical with large projects, it is recommended to use a _git shallow clone_ in such instances unless you really need the full history.

https://www.perforce.com/blog/141218/git-beyond-basics-using-shallow-clones

**Comment by menuet** [comment]
Yes, I know about --depth X, but even with --depth 1, it takes a long time.
And when I use --depth X, I have problems retrieving some branches, because some of them began before the Xth commit.
Also, when there is a huge repository, with many non-text files, the git status command becomes slow too over time.
Finally, my point is : most of the big files are doc files. The source files alone really take 10% of the space. It may be a good thing to separate them.

**Comment by GregLee-TR** [comment]
Thanks for bringing this to our attention.  We found that our use of the Preview branch bloated the repo quite a bit.  We have cleaned that out and are looking at options on properly handling our documents.
