### ISSUE TITLE
What is the reason for StatusMsg "No Change"

### ISSUE THREAD

**Issue by leichtundkross** [thomsonreuters/Elektron-SDK#16]
When I am requesting a Market Price I am facing the problem that the day's first request doesn't result in a valid refresh message. Instead I am receiving a StatusMsg of this kind:
```
StatusMsg
    streamId="6"
    domain="MarketPrice Domain"
    state="Open / No Change / None / '*SERVICE_NAME: Requested'"
    name="..."
    serviceId="..."
    serviceName="..."
StatusMsgEnd
```
If a send a second request message I will receive the expected RefreshMsg.

This is the ReqMsg I am sending:
```
ReqMsg reqMsg = EmaFactory.createReqMsg();
reqMsg.serviceName("...")
    .name("...")
    .domainType(DomainTypes.MARKET_PRICE);
```

To be a little more precise: The problem seems to occur for every request after the system has been idle for a while (at least the client did not send any requests).

Am I missing something in my request configuration or is it an issue on the provider or framework side?

**Comment by GregLee-TR** [comment]
A Status message may be received depending upon the state of the upstream service. 

You might try enabling tracing to determine actual message flow (In EmaConfig.xml, set XmlTraceToStdout value="1", and LoggerSeverity::Verbose)

I hope this helps.

**Comment by GregLee-TR** [comment]
If you continue to have issues or questions on this topic, please make sure to visit the Q&A forums on the Developer Portal (http://developers.thomsonreuters.com) or open a support ticket through RDC.
