### ISSUE TITLE
Plan to release ema.jar, upa.jar, ... into public Maven repo?

### ISSUE THREAD

**Issue by laysakura** [thomsonreuters/Elektron-SDK#17]
Hi,

If you provide
- ema.jar
- upa.jar
- upaValueAdd.jar

and such things into public Maven repository, users do not have to `ant build` by themselves.

Actually, I'm using Scala and having hard time to write `build.sbt` to clone this repo as submodule, `ant build` and add the above JARs into classpath,
while it is really simple if JARs are available in some maven repo.

Thanks,

**Comment by seba5** [comment]
Hi Sho,

we do provide the above jar files via the Developer Portal. Please follow the link below to the Elektron SDK Java Developer Portal. 
https://developers.thomsonreuters.com/elektron/elektron-sdk-java

**Comment by laysakura** [comment]
thank you.
But it seems I need to login to get the JAR files.

If they are registered in public maven repository, only I have to do is specifying the JARs' URL with their versions in libraryDependencies in build.sbt file.

**Comment by DenisDollfus** [comment]
Did you try to manage them as "unmanaged dependencies" as described here http://www.scala-sbt.org/1.0/docs/Library-Dependencies.html?

**Comment by gotson** [comment]
+1 for deploying in MavenCentral, that would make it much easier for everyone to import the library into a project.

Adding the jars manually has a few drawbacks:
- you still need to manually specify the dependencies of the Elektron SDK, either the external ones (like the apache common libraries), or the internal ones (like `upa` and `upaValue`). Having the dependencies managed by Maven would make our own project dependencies clearer, by only having the direct dependencies we need, instead of listing dependencies of other libraries.
- upgrading the libraries to a newer version requires to download the new jars, instead of just changing the version number using Maven
- linking the jars directly in our project adds complexity on the code repository

**Comment by BrianSandri** [comment]
As we continue to work towards open sourcing the ETA portion of ESDK, we are looking into packaging/deployment changes that can help provide additional ease of use. Maven is one of the options we will investigate as part of this effort.

**Comment by addicticks-dev** [comment]
You may want to have a look at [this issue](https://github.com/thomsonreuters/Elektron-SDK/issues/21). While it doesn't provide the artifacts in Maven Central it is certainly a step on the way. 

In my org we have our own internal Maven Repo and we then just upload the artifacts from the project referenced in said issue. Most Java-based organizations would have such a company-wide repo, typically there's a place in there for "3rd party artifacts". 

Once the Elektron SDK was Mavenized, actually getting the artifacts (with javadocs and source, of course) into our repo was a matter of minutes.

/Lars

**Comment by BrianSandri** [comment]
We have seen several requests for Maven and we are planning to take a look at this in the near future. Thank you for the time you have spent to restructure and make the layout more Maven-like. This will help the team hit the ground running as we begin investigation.

**Comment by seba5** [comment]
We have just made the preview branch available for download that contains updates to make use of gradle for Java and cmake for Cpp-C. Please take a look and let us know your thoughts.
We are still planning to make the ESDK distribution available on MavenCentral. Updating the build environment for Java to use gradle is the first step.

**Comment by seba5** [comment]
We went ahead and uploaded the upcoming release as a SNAPSHOT to maven central. Take note that the SNAPSHOT jars are not yet fully tested! We decided to make it available prior to the official release to garner community feedback on the availability of the jars on maven central

I have attached a sample build.gradle file showing the location of the SNAPSHOT jar file for EMA.
[build.gradle.txt](https://github.com/thomsonreuters/Elektron-SDK/files/1811521/build.gradle.txt)

Thanks.

**Comment by seba5** [comment]
Hi All,

the Elektron-SDK 1.2.0 Java is now published on Maven Central:

[ema-3.2.0.1.jar](https://search.maven.org/#artifactdetails%7Ccom.thomsonreuters.ema%7Cema%7C3.2.0.1%7Cjar)
[upaValueAdd-3.2.0.1.jar](https://search.maven.org/#artifactdetails%7Ccom.thomsonreuters.upa.valueadd%7CupaValueAdd%7C3.2.0.1%7Cjar)
[upa-3.2.0.1.jar](https://search.maven.org/#artifactdetails%7Ccom.thomsonreuters.upa%7Cupa%7C3.2.0.1%7Cjar)`
[upaValueAddCache-3.2.0.1.jar](https://search.maven.org/#artifactdetails%7Ccom.thomsonreuters.upa.valueadd.cache%7CupaValueAddCache%7C3.2.0.1%7Cjar)
[ansipage-3.2.0.1.jar](https://search.maven.org/#artifactdetails%7Ccom.thomsonreuters.upa.ansi%7Cansipage%7C3.2.0.1%7Cjar)
