### ISSUE TITLE
JavaScript version of lib

### ISSUE THREAD

**Issue by maZahaca** [thomsonreuters/Elektron-SDK#18]
Hello,

Currently in the Preview branch / Js folder there is nothing. Are going to release something soon?

**Comment by IainScott** [comment]
We have no imminent preview changes planned for our current JavaScript API (EWA)

We are working on a JSON/Websocket API for our platform.  For that we'll have various samples including JS and these will be included here when ready.

Note that this is still in the early stages of development on the platform side so we don't have a release date yet.

Thanks

Iain
