### ISSUE TITLE
consumer.registerClient with Domain Type SOURCE throws NullPointerException in case first channel connection failure

### ISSUE THREAD

**Issue by ZhangLizeng** [thomsonreuters/Elektron-SDK#23]
With EMAJ 1.0.8, I'm trying to get channel event (up/down) with below sample code: 

consumer.registerClient(EmaFactory.createReqMsg().domainType(DomainTypes.SOURCE), channalStatusClient);

I use ChannelSet in "EmaConfig"
<ChannelSet value="Channel_1, Channel_2"/>

It's ok if "Channel_1" is good. But in case "Channel_1" failure & "Channel_2" is good, I got NPE when registerClient.

Call stack:
Exception in thread "main" java.lang.NullPointerException
	at com.thomsonreuters.ema.access.DirectoryItem.submit(DirectoryCallbackClient.java:952)
	at com.thomsonreuters.ema.access.DirectoryItem.open(DirectoryCallbackClient.java:810)
	at com.thomsonreuters.ema.access.ItemCallbackClient.registerClient(ItemCallbackClient.java:1745)
	at com.thomsonreuters.ema.access.OmmBaseImpl.registerClient(OmmBaseImpl.java:350)
	at com.thomsonreuters.ema.access.OmmConsumerImpl.registerClient(OmmConsumerImpl.java:73)

Also, please kindly advise is this the right way to hook the channel event.  Thank you.

**Comment by maydu** [comment]
Thank you for providing feedback to us. Sorry for our delayed response.
EMA allows applications to consume and provide OMM data at the message level of the API stack. Therefore one of ease-of-use ways from EMA is hiding all connection detail which client has no need to worry about. So there is no channel, connection event or these kind of public interfaces exposed to client application. Client can just create a Ema consumer, then start to send item requests without concerning all connection, login, dictionary or directory detail.
In your case you have configured multiple channels in “ChannelSet”. There is a way that client can tell which channel has been used/connected by turning on EMAJ logger. You can see something like this from EMA logger:

May 23, 2017 11:42:54 AM com.thomsonreuters.ema.access.ChannelCallbackClient reactorChannelEventCallback
WARNING: loggerMsg
    ClientName: ChannelCallbackClient
    Severity: Warning
    Text:    Received ChannelDownReconnecting event on channel Channel_3
	RsslReactor Channel is null
	Error Id 0
	Internal sysError 0
	Error Location Reactor.processWorkerEvent
	Error text Error initializing channel: errorId=-1 text=Connection refused: no further information
loggerMsgEnd


May 23, 2017 11:42:55 AM com.thomsonreuters.ema.access.ChannelCallbackClient reactorChannelEventCallback
INFO: loggerMsg
    ClientName: ChannelCallbackClient
    Severity: Info
    Text:    Received ChannelUp event on channel Channel_1
	Instance Name Consumer_1_1
	Component Version RFA Java Edition 8.0.0.L1.all.xdev2
loggerMsgEnd

If you don’t mind, can I know the reason your application needs channel info? This may help us to understand how client uses our APIs, and it definitely helps us to continue improving our API.

Also client can call registerClient() with login request, then processes login response state to determine if a connection is up. In general, a login response of stream state “OPEN”,data state “OK”, means that a connection is up, the provider accepts the login user, and ready for consumer to send requests. Please see example330__Login__Streaming from the EMA package how to send a login request by EMA client.
We also identified the NPE issue you saw before. We created a ticket ESDK-602 for our future reference and fix. 

Thanks again for your support.
May

**Comment by maydu** [comment]
The issue has been fixed in the Elektron-SDK_1.1.1 release. Thank you for your support.
