### ISSUE TITLE
JS version?

### ISSUE THREAD

**Issue by markhealey** [thomsonreuters/Elektron-SDK#27]
The readme in `master` points to a `JS preview` but there's nothing in it. Plans or update for this version?

**Comment by BrianSandri** [comment]
The Javascript version was aspirational, but we believe that the new JSON Websocket API work being done may satisfy the needs of users for Javascript, Perl, Python, and other languages that we do not have native libraries available in.  It is currently in early access phases, but the documentation and EAP package containing examples are available here on the developer community:  
https://developers.thomsonreuters.com/elektron/websocket-api-early-access
If you have a few minutes, please take a look and feel free to email any feedback to me at brian.sandri@thomsonreuters.com.  You will need to log in, but it is free to create this.   I will also revise our readme to remove the JS references for now. 
Thank you!
Brian
