### ISSUE TITLE
Is it possible to submit a Map with summary only (with no entry)?

### ISSUE THREAD

**Issue by ZhangLizeng** [thomsonreuters/Elektron-SDK#28]
Hi,  All
I'm using EMAJ 1.0.8.  Tried to submit a Map with summary only but failed to do so, got various exceptions when payload(the map without entry.). Please advise.  Thank you.   Below is sample code. 

		FieldList mapSummaryData = EmaFactory.createFieldList();
		mapSummaryData.add(...);   //Meaningful summary data.

		Map map = EmaFactory.createMap();
		map.summaryData(mapSummaryData);

                //Meaningless map entry, but I had to add one here, otherwise .payload will throw exception.
		FieldList entryData = EmaFactory.createFieldList();
		map.add(EmaFactory.createMapEntry().keyAscii("", MapEntry.MapAction.ADD, EmaFactory.createFieldList()));

		provider.submit(
				EmaFactory.createRefreshMsg().domainType(EmaRdm.MMT_SYMBOL_LIST)
						.serviceName("DIRECT_FEED").solicited(true).clearCache(true).state(OmmState.StreamState.OPEN,
								OmmState.DataState.OK, OmmState.StatusCode.NONE, "Refresh Completed")
						.payload(mapSummaryData)
						.complete(true),
				itemHandle);

**Comment by BrianSandri** [comment]
This functionality was intentionally omitted in EMA for now as it was not expected to be a common use case and the team wanted to focus on more of the core behavior set.  We do have a JIRA to remove the exception and add the functionality needed to allow this, as users can do this at ETA beneath EMA today.  We are projecting that the JIRA will be pulled into one of our sprints in the coming months and when this functionality becomes available for both C++ and Java, we will release it here first!  Thanks for your patience, we will let you know when this becomes available.

**Comment by ZhangLizeng** [comment]
Hi, Brian
Any update? We currently had to put an meaningless entry, which caused confusion to consumers. Hoping SDK enhancement here.  Thanks.

**Comment by bberner** [comment]
This will be fixed in the release scheduled for Q1 2018.

**Comment by bberner** [comment]
Fixed in ESDK 1.2.0 release.
