### ISSUE TITLE
Programmatic configuration

### ISSUE THREAD

**Issue by thomasthebaker** [thomsonreuters/Elektron-SDK#29]
When will you support programmatic configuration? The current configuration utilities are very basic and I can't configure what I want (different nodes per environment with automatic failover). 

There are two main problems that could do with some attention:

1. The config object is cast to the internal object implementation. What is the point of the interface if users can't supply their own implementation? It would be much nicer if you actually read the config from a true interface and then I can supply my own implementation that I can manipulate myself:

https://github.com/thomsonreuters/Elektron-SDK/blob/089895c99f332eddff00ca70cddcec83d7384b82/Java/Ema/Src/main/java/impl/com/thomsonreuters/ema/access/OmmConsumerImpl.java#L38

2. Programmatic configuration has not been implemented yet (but stubs exist). This is a key feature for us to use across our production, integration and dev environments. In real production systems just being able to set the single host name (current state of Elektron config), is not sufficient for connection resiliency:
https://github.com/thomsonreuters/Elektron-SDK/blob/7213c3a5c48200aceda6776a262be07c9ae5a31b/Java/Ema/Src/main/java/impl/com/thomsonreuters/ema/access/EmaConfigImpl.java#L561

**Comment by soranat** [comment]
For the first question, the OmmConsumerConfig is write only interface which needs to have its own implementation to read and configure the behavior of OmmConsumer. The internal implementation also has its own business login to query additional configuration parameters from the EmaConfig.xml file or programmatic configuration database(when it is available for EMAJ).

For the second question, EMAJ has a requirement to implement the programmatic configuration in upcoming releases. You can configure multiple host names with the ChannelSet element in the EmaConfig.xml file for connection resiliency.

**Comment by thomasthebaker** [comment]
Thanks for the reply. It would be good to have the programmatic configuration soon as it's quite difficult to configure efficiently at the moment. I did manage to use ChannelSet for the OmmConsumer which worked really well. The ChannelSet doesn't get used properly by the OmmNiProvider, I've raised that as a separate issue.

**Comment by bberner** [comment]
Fixed with ESDK 1.2.1.L1 release.
