### ISSUE TITLE
Supported platforms?

### ISSUE THREAD

**Issue by nkuln** [thomsonreuters/Elektron-SDK#3]
I worked with some of these APIs before and am thrilled to see this available on GitHub :-)

Having tried to build and ETA and run some examples on my Ubuntu, I think the instructions (README.md) didn't emphasize enough about the supported platforms. Looking at the makefile, this only builds on RedHat, SUSE, Oracle Linux, it seems? (also, shouldn't `makefile all` command be instead `make all`?)

**Comment by BrianSandri** [comment]
Grant, 
Thank you for using the product!  I have incorporated your feedback into the ETA README.md file.  Please let us know of any other issues or feedback.  
Thanks!

**Comment by jgidding** [comment]
If you would like to make any modifications that allow it to build on Ubuntu, we'd be willing to evaluate your PR.
