### ISSUE TITLE
OmmNiProviderConfigImpl returns null instead of this

### ISSUE THREAD

**Issue by thomasthebaker** [thomsonreuters/Elektron-SDK#31]
The OmmNiProviderConfigImpl returns null for the two addAdminMsg methods. This conflicts with the documentation and all the other methods where you expect the method to return a reference to this object.

Documentation:
https://github.com/thomsonreuters/Elektron-SDK/blob/master/Java/Ema/Src/main/java/interface/com/thomsonreuters/ema/access/OmmNiProviderConfig.java#L169

Incorrect implementation:
https://github.com/thomsonreuters/Elektron-SDK/blob/master/Java/Ema/Src/main/java/impl/com/thomsonreuters/ema/access/OmmNiProviderConfigImpl.java#L125

**Comment by maydu** [comment]
Tom,
Thanks for helping us to identify this issue. We will create a ticket for it. And provide the fix in the future release.

**Comment by maydu** [comment]
This issue has been captured in ESDK-652.

**Comment by thomasthebaker** [comment]
Thanks for the fast response.
Tom

**Comment by maydu** [comment]
This issue has been fixed in the Elektron-SDK_1.1.1 release. Thank you for your support.
