### ISSUE TITLE
Deadlock in EMA C++ 1.1.0 while reissuing the request message

### ISSUE THREAD

**Issue by jirapongse-thomsonreuters** [thomsonreuters/Elektron-SDK#35]
This issue is from [this question](https://community.developers.thomsonreuters.com/questions/15831/ommconsumer-reissue-problem.html). 

I can replicate the issue by modifying the example (Consumer100) and using breakpoint to freeze and run threads.

The modified code is:
`
void AppClient::onRefreshMsg( const RefreshMsg& refreshMsg, const OmmConsumerEvent& e) 
{
	cout << refreshMsg << endl;		// defaults to refreshMsg.toString()
	consumer.reissue(ReqMsg().serviceName("API_ELEKTRON_EPD_RSSL").name("IBM.N"), e.getHandle());
}
int main( int argc, char* argv[] )
{ 
	try { 
		
		consumer.registerClient( ReqMsg().serviceName( "API_ELEKTRON_EPD_RSSL" ).name( "IBM.N" ), client );
		consumer.registerClient(ReqMsg().serviceName("API_ELEKTRON_EPD_RSSL").name("CNY="), client);
		sleep( 60000000 );				// API calls onRefreshMsg(), onUpdateMsg(), or onStatusMsg()
	} catch ( const OmmException& excp ) {
		cout << excp << endl;
	}
	return 0;
}
`
When the application receives refreshMsg, it will call reissue. The deadlock happens when the main thread is calling OmmConsumer.registerClient() while EMA thread (API Dispatch Mode) is in onRefreshMsg callback.

The call stack of the EMA thread will look like:
![emathread](https://user-images.githubusercontent.com/18653647/29702891-68a6e9ba-899d-11e7-80e2-a76a2a307a3c.png)

The call stack of the main thread will look like:
![mainthread](https://user-images.githubusercontent.com/18653647/29702905-74491658-899d-11e7-96be-b6c4634b3bc3.png)

**Comment by soranat** [comment]
This issue is captured with tracking number ESDK-582 which will be fixed in next maintenance release.

**Comment by maydu** [comment]
This issue has been fixed in the Elektron-SDK_1.1.1 release. Thank you for your support.
