### ISSUE TITLE
Callback methods are not called after EMA Java receives a STATUS message

### ISSUE THREAD

**Issue by nipat-kunvutipongsak** [thomsonreuters/Elektron-SDK#37]
When a Consumer application receives a STATUS message. The onAllMsg and onUpdateMsg callback methods won't be called anymore when EMA Java application receives further updates.

Source code files for problem reproduction:
[EMAJ_callback_not_called.zip](https://github.com/thomsonreuters/Elektron-SDK/files/1378052/EMAJ_callback_not_called.zip)

Additional log to investigate this issue is below:
[emaj_callbacks_are_not_called_log.txt](https://github.com/thomsonreuters/Elektron-SDK/files/1378026/emaj_callbacks_are_not_called_log.txt)

This behavior hasn't occurred in other APIs such as RFA Java, or EMA C++.

**Comment by bberner** [comment]
Thank you for the detailed information. We will fix in the next release.

**Comment by tmurthy** [comment]
Nipat,
is this something you found or a customer issue

**Comment by nipat-kunvutipongsak** [comment]
@tmurthy It’s the customer‘s issue.
Here’s the source:https://community.developers.thomsonreuters.com/questions/18697/the-connection-between-my-application-and-the-reut.html

**Comment by seba5** [comment]
This issue has been fixed with the newest Elektron-SDK_1.1.2.G1 release.
