### ISSUE TITLE
EMA - Impossible to access config inside OmmConsumer

### ISSUE THREAD

**Issue by TD-BNP** [thomsonreuters/Elektron-SDK#38]
Hello,
Let me explain my situation: I have a Consumer application that connects to several ads servers depending on the source we want to reach (for example ads-idn for IDN_SELECTFEED). The problem in EMA is we can declare several Consumer in the EmaConfig.xml but in our Consumer application we can use only one Consumer at a time: createOmmConsumerConfig ().consumerName (name).
Am I right or is there any solution I don't know?

So, as I need to create in my application one Consumer for each ads/source, I need for access to the OmmConsumerConfig. Nevertheless, this interface doesn't expose any methods to retrieve all the consumers declared in the EmaConfig.xml (ConsumerGroup) and the implementation class OmmConsumerConfigImpl is not accessible (as the XmlConfigReader which would be so useful...).
Is there any way to change it? By adding methods in the interface OmmConsumerConfig or by declaring more classes as public? Or is there another way to access the information inside my OmmConsumerConfig?

Thanks.

**Comment by maydu** [comment]
Hi,
Yes, you can create several OmmConsumer instances in your consumer application. Each OmmConsumer instance will connect to one ads-source. 
You also can manage consumer instances by passing consumer names in your app such as:

OmmConsumerConfig.consumerName("Consumer_1"); 
the code above tells EMA will create an OmmConsumer instance with <Consumer> tag of value "Consumer_1" in EmaConfig.xml 

And the following function call will return consumer instance name, such as Consumer_1_1 (last 1 means instance id, which will increase by 1 if there are more same configured instance names)
OmmConsumer.consumerName() ;
 
Can you tell me what other information you app needs to retrieve from OmmConsumerConfig?
And are you using EMAJ or EMACPP?

Thanks,
May

**Comment by TD-BNP** [comment]
Hi,
Thanks for your answer. I am using EMAJ.
I cannot use your solution (Consumer_1_1 with increasing id) because I want to retrieve all the Consumer defined in my EmaConfig and I dont know how many there are.
So now I have to write a method to read and parse my xml config file, but it is a bad solution as I rewrite what is already written in the XmlConfigReader.
Why are all methods of OmmConsumerConfigImpl not declared in the interface OmmConsumerConfig? Why are XmlConfigReader and other tools not public?

**Comment by TD-BNP** [comment]
Sorry I closed the issue not on purpose.

**Comment by maydu** [comment]
Hi,
All consumers defined in your EmaConfig.xml don't mean anything until your application specifies which consumer will be created by passing consumerName on OmmConsumerConfig instance (there is only one exception, you app will always use the DefaultConsumer if your app has no consumername passing.
That says that your app has to know and specify which consumer (consumer name) will be created, then EMA api will look for that specified consumername section in EmaConfig.xml for the channel related config info to connect to the provider.

**because I want to retrieve all the Consumer defined in my EmaConfig** 
 >Can you tell me why you need to retrieve all the Consumer defined in EmaConfig since all these info defined by you, and also there is no need for EMA app to know  what is defined inside the file. 
>Is your EmaConfig.xml is not static, it could change anytime? So your app has to be written in the way which can read consumer names from EmaConfig file?
>Can you provide us with your usage case such as steps (flow chart) in your app in order to help us understand you more?

**Comment by TD-BNP** [comment]
Hi,
Indeed my app need to know which consumers are in the EmaConfig.xml.
Let me explain shortly the purpose:
our infra team has provided us several separated servers, one server per source. For example for IDN_SELECTFEED we reach ads-idn, for GDCSTU the ads-stu...
So in our app, that is a lib used by other apps,
we create a method that takes the source and the product code as parameters and return the rt values (Ask, Bid...).
Inside the method, we choose the consumer to call depending on the source, among all consumers presents in the EmaConfig, each Consumer being linked to one ads so one source.

And because the source is specified in a properties file, we can have an app source code that never changes, only EmaConfig and properties files changed synchroneously.

Why do we have this kinf of architecture? Because before Ema we used RFA, that creates all connections to all ads defined in the config.xml., and then switch to one or another connection depending on the source. And the app had never to do to read the config file.

**Comment by maydu** [comment]
Hi,
Thank you very much for making effort to let us know what your app is doing. I get the picture now.

Yes, RFA does allow one consumer, one session with multiple connections, also provides servicegroup feature (group diff sources from diff conns) which allows client to route any of concrete service/source in the servicegroup without knowing any connection info.

EMA has some limitation in your usage. 
For a workaround, you app has to read all consumer names from EmaConfig.xml by your own app or passing consumer names as application arguments. In this way, your app source code will never need to change. After creating all consumer instances (per conn, per consumer), your app can register for source directory request on each consumer, then cache all source names mapping with consumer instances.

If other apps set the source and the product code to your app (lib), your app looks up the cache, then know how to route client's request to which source/consumer instance, right?

Hope this can help a little.
Thanks again.
May

**Comment by TD-BNP** [comment]
And about the "internal" implementation classes (OmmConsumerConfigImpl) for example, is there any reason for their method not being exposed in the interface OmmConsumerConfig? Why is the information inside an OmmConsumerConfifmg hidden?

**Comment by maydu** [comment]
OmmConsumerConfig interface is designed for client to set config info, not for reading. We may consider to provide a public interface for accessing config info as a plus ( or an value add) in the future.

**Comment by TD-BNP** [comment]
Thanks for your help.
