### ISSUE TITLE
Support for encrypted RSSL connection

### ISSUE THREAD

**Issue by ardyesp** [thomsonreuters/Elektron-SDK#39]
When would **RSSL_ENCRYPTED** become available in EMA Java. Thanks.

**Comment by bberner** [comment]
This functionality is expected to be in the next release.

**Comment by wleblanc** [comment]
Bill,  When is the expected next release of the EMA Java?

**Comment by bberner** [comment]
Somewhere around the end of year or early next year.

**Comment by bberner** [comment]
RSSL_ENCRYPTED for EMA Java was put on GitHub a few weeks ago.
