### ISSUE TITLE
Can't find the ETA package on Customer Zone.

### ISSUE THREAD

**Issue by dicko99** [thomsonreuters/Elektron-SDK#4]
Hi there,

When I sign into Customer Zone and navigate to the software download page I cannot see the Elektron API package listed. Do I need to be permissioned to download this?

Regards,
Richard.

**Comment by GregLee-TR** [comment]
Richard,

If you have a Customer Zone account you should be able to get access to the download.   When you go to the site as you state above, are you able to choose the **Category: MDS - API** and **Products: Elektron SDK C++** as shown below?
![esdk_etabin_downloadimage](https://cloud.githubusercontent.com/assets/11496122/9138080/71564a10-3ce7-11e5-8cfc-0c50eacdcb64.png)


I hope this helps.  If you still can't get to the download, please feel free to reach back out to me.

**Comment by dicko99** [comment]
Greg,

Here's what I see under MDS - API:

No sign of the Elektron SDK C++ product...

Regards,
Richard.
​

**Comment by GregLee-TR** [comment]
I looked into this and it appears to be related to Customer Zone permissioning as you suspected. Please contact your Technical Account Manager (TAM) to have your permissions set properly.

**Comment by GregLee-TR** [comment]
README.md was updated to specify TRDC membership requirement for the ETA binary download.
