### ISSUE TITLE
NiProvider LoginRequestTimeOut affects overall message rate performance.

### ISSUE THREAD

**Issue by thomasthebaker** [thomsonreuters/Elektron-SDK#49]
Hi,
We're seeing some strange behaviour. We have an NiProvider application and a load test that runs our application at 50k msg/sec. The load test publishes the messages and then records them coming back in through it's own subscriptions. 

We're tuning some of the EmaConfig.xml values. Our baseline value for LoginRequestTimeOut is 1000, if I set this higher to 30000 then the test can only produce 25k msg/sec, if I set it to 0 (disabling the timeout), the same thing happens. That is the only parameter I change between runs and it's the same every time. I don't understand how this parameter should affect ongoing application performance. I even added a 10 second wait after sending initial Image data for all the subjects before starting the higher message rate load test. It looks like the parameter is used here:

https://github.com/thomsonreuters/Elektron-SDK/blob/87d0e47d17de6b321f61ee34df4cf218b058f227/Java/Ema/Src/main/java/impl/com/thomsonreuters/ema/access/OmmBaseImpl.java#L966

How does the LoginRequestTimeOut parameter go on and affect overall application throughput? Is there something else that needs to be included in the documentation to help us set a good value. From the documentation it looks like it should be fine to allow a bit longer for the initial login request to complete. From our test we're seeing that this is detrimental to application performance. Can you provide any guidance or explanation?

**Comment by maydu** [comment]
Hi,
I used example250_MarketPrice_performance (shipped with esdk package) to do a quick test with diff values ( 45000, 30000, 1000, 0) of LoginRequestTimeOuts, the results are not much difference. Here is the record rates.

&&&&&&&&_activeConfig.loginRequestTimeOut 45000

total refresh count = 50000
total time = 1.081 sec
refresh rate = 46253.47 refresh per sec
update count = 50000
update rate = 30266.346 update per sec
update count = 50000
update rate = 33557.047 update per sec
update count = 50000
update rate = 36127.168 update per sec
update count = 50000
update rate = 37313.434 update per sec
update count = 50000
update rate = 36443.15 update per sec
update count = 50000
update rate = 37341.3 update per sec
update count = 50000
update rate = 36954.914 update per sec
update count = 50000
update rate = 37341.3 update per sec
update count = 50000
update rate = 37425.152 update per sec
update count = 50000
update rate = 37064.492 update per sec
update count = 50000
update rate = 36791.758 update per sec
update count = 50000
update rate = 36258.16 update per sec
update count = 50000
update rate = 36101.082 update per sec

&&&&&&&&_activeConfig.loginRequestTimeOut 30000

total refresh count = 50000
total time = 1.025 sec
refresh rate = 48780.49 refresh per sec
update count = 50000
update rate = 30543.678 update per sec
update count = 50000
update rate = 33134.527 update per sec
update count = 50000
update rate = 35637.918 update per sec
update count = 50000
update rate = 36982.25 update per sec
update count = 50000
update rate = 35893.754 update per sec
update count = 50000
update rate = 35893.754 update per sec
update count = 50000
update rate = 35893.754 update per sec
update count = 50000
update rate = 35765.38 update per sec
update count = 50000
update rate = 35868.004 update per sec
update count = 50000
update rate = 36337.207 update per sec
update count = 50000
update rate = 35739.812 update per sec
update count = 50000
update rate = 35236.082 update per sec
update count = 50000
update rate = 35211.27 update per sec
update count = 50000
update rate = 36179.45 update per sec

&&&&&&&&_activeConfig.loginRequestTimeOut 1000

total refresh count = 50000
total time = 1.213 sec
refresh rate = 41220.113 refresh per sec
update count = 50000
update rate = 28555.111 update per sec
update count = 50000
update rate = 30921.459 update per sec
update count = 50000
update rate = 35310.734 update per sec
update count = 50000
update rate = 35561.88 update per sec
update count = 50000
update rate = 36710.72 update per sec
update count = 50000
update rate = 37009.625 update per sec
update count = 50000
update rate = 36982.25 update per sec
update count = 50000
update rate = 36982.25 update per sec
update count = 50000
update rate = 36982.25 update per sec
update count = 50000
update rate = 36791.758 update per sec
update count = 50000
update rate = 35612.535 update per sec


&&&&&&&&_activeConfig.loginRequestTimeOut 0

total refresh count = 50000
total time = 1.05 sec
refresh rate = 47619.05 refresh per sec
update count = 50000
update rate = 30543.678 update per sec
update count = 50000
update rate = 33156.5 update per sec
update count = 50000
update rate = 36549.707 update per sec
update count = 50000
update rate = 37453.184 update per sec
update count = 50000
update rate = 36576.445 update per sec
update count = 50000
update rate = 37009.625 update per sec
update count = 50000
update rate = 35893.754 update per sec
update count = 50000
update rate = 36231.883 update per sec
update count = 50000
update rate = 36205.65 update per sec
update count = 50000
update rate = 36443.15 update per sec
update count = 50000
update rate = 35893.754 update per sec
update count = 50000
update rate = 35211.27 update per sec
update count = 50000
update rate = 36179.45 update per sec
update count = 50000
update rate = 36549.707 update per sec
update count = 50000
update rate = 36523.01 update per sec 

Can you send your EmaConfig.xml file for us to take a look at?
Does your app use api dispatch or user dispatch mode? 
Does your app use channelset feature?

**Comment by thomasthebaker** [comment]
Hi Maydu, 
Sorry for the delay. Let me see if I can reproduce as you suggested and then I'll get back to you. 
Thanks
Tom

**Comment by maydu** [comment]
Tom,
Did you have a chance to reproduce this issue? Let us know. Thanks.

**Comment by vlevendel** [comment]
@thomasthebaker Any update on this thread?

**Comment by thomasthebaker** [comment]
Hi,
We haven't had a chance to investigate this further. If you want to close off for now then we're happy with that.
Thanks
Tom
