### ISSUE TITLE
Infinite loop in RmtesBufferImpl.cpp

### ISSUE THREAD

**Issue by steve16351** [thomsonreuters/Elektron-SDK#5]
Hi,

I'm having a problem using the EMA API when processing an update on field 1352 with an RmtesEnum type. I can reproduce the issue with the Consumer200 example by adding this to the `decode` method:

    case DataType::RmtesEnum:			
        cout << fe.getRmtes().toString();
	break;

And registering an ongoing interest in BOL.ST and ALFA.ST.

When an update is received on field 1352, sometimes it will loop infinitely in RmtesBufferImpl.cpp in this `while` loop if it is entered:

    RsslRet retCode = rsslRMTESApplyToCache( &_rsslBuffer, &_rsslCacheBuffer );
    while ( RSSL_RET_BUFFER_TOO_SMALL == retCode )
		{
			free( _rsslCacheBuffer.data );

			_rsslCacheBuffer.length += _rsslCacheBuffer.length;

			_rsslCacheBuffer.data = (char*)malloc( _rsslCacheBuffer.allocatedLength );
			if ( !_rsslCacheBuffer.data )
			{
				throwMeeException( "Failed to allocate memory in RmtesBufferImpl::apply( const char* , UInt32 )" );
				return;
			}
		}

Is this something you can help with?

Thanks

**Comment by seba5** [comment]
Hi,

this appears to be a bug in our code. Inside the while there should be code that calls the 
retCode = rsslRMTESApplyToCache 
method after allocating a bigger buffer.

**Comment by MitchellKatoTR** [comment]
Also, make sure you're incrementing the rsslCacheBuffer's allocatedLength, not the length.

rsslRMTESApplyToCache uses that the allocatedLength to determine the buffer length.  rsslCacheBuffer.length is used to determine the total amount of memory used by the buffer.

**Comment by seba5** [comment]
Submitted a fix for this issue.
