### ISSUE TITLE
== should not be used for NaN values

### ISSUE THREAD

**Issue by thomasthebaker** [thomsonreuters/Elektron-SDK#51]
Hi, 
I've found a bug in the RealImpl where a Double.NaN value is checked using the == operator. A NaN is never equal to another NaN and so Double.isNaN() method should be used. 

The two places below should be fixed, it prevents encoding via the double/float value methods and is a bug as it's an impossible to reach if block:

https://github.com/thomsonreuters/Elektron-SDK/blob/5de03f853286e7c242997b7ca1cd44da9617256f/Java/Eta/Source/impl/com/thomsonreuters/upa/codec/RealImpl.java#L82

https://github.com/thomsonreuters/Elektron-SDK/blob/5de03f853286e7c242997b7ca1cd44da9617256f/Java/Eta/Source/impl/com/thomsonreuters/upa/codec/RealImpl.java#L118

There may be other places within ETA and EMA where this is an issue, I guess it's worth have a quick grep over the codebase.
Thanks
Tom

**Comment by bberner** [comment]
Thanks for your feedback. We'll investigate and make any necessary changes in a future release.

**Comment by bberner** [comment]
Fixed with latest GitHub push with tag Elektron-SDK_1.2.0.2.G1.
