### ISSUE TITLE
Java : Gradle build script must not rely on working dir

### ISSUE THREAD

**Issue by addicticks-dev** [thomsonreuters/Elektron-SDK#52]
The Gradle build script fails when executed from my IDE. The reason is the `cloneBinaryPack` which makes assumptions about working dir. I'm no Gradle expert but I've understood as much as that such an assumption must never exist in a Gradle build script ..  even if it seems to work well for some types of executions.

Here's the offending code:
```gradle
doLast {
        // check if we are in GSG package
        File gsgDir = new File('../Elektron-SDK-BinaryPack')     // bad, makes assumptions on working dir
        if (!gsgDir.exists()) {
            // if not in GSG package try to clone BinaryPack
            File dir = new File('../Elektron-SDK-BinaryPack')  // bad, makes assumptions on working dir
            if (!dir.exists()) {
```

and here's the fix:

```gradle
doLast {
        // check if we are in GSG package
        File gsgDir = file('../Elektron-SDK-BinaryPack')
        if (!gsgDir.exists()) {
            // if not in GSG package try to clone BinaryPack
            File dir = file('../Elektron-SDK-BinaryPack')
            if (!dir.exists()) {
```

(i.e. use the `file()` method instead of `new File()`)

**Comment by seba5** [comment]
Hi, can you let us know which IDE are you using, thanks?

**Comment by addicticks-dev** [comment]
NetBeans ... but that should be irrelevant. I _can_ make it work, if I really want to because NetBeans offers the choice if I want to alternatively use the gradle launcher for executions (i.e. use `gradle.bat` as opposed to using direct IDE integration via Gradle Tooling API). I'm just pointing out that the build will break whenever you put it an environment where the assumption does not hold true. I image some CI platforms will bring trouble as well. :-)

**Comment by seba5** [comment]
The fixed has been pushed.
