### ISSUE TITLE
RSSL_ASSERT failure when building Map large enough to require reallocation

### ISSUE THREAD

**Issue by DuncanSands** [thomsonreuters/Elektron-SDK#54]
This occurs if you do a debug build of Eta (which enables RSSL_ASSERT) and construct such a large Map that a memory reallocation is required.

Actual output (requires debug build of Eta):

$ ./BigMap 
Fatal Error: _levelInfo->_encodingState == RSSL_EIS_ENTRIES, Unexpected encoding attempted (file .../Eta/Impl/Codec/mapEncoder.c, line 425)
Aborted (core dumped)

Expected output (which you get with an optimized Eta build): should execute silently and without error

$ ./BigMap
$

Testcase:

#include "Ema.h" 
using namespace thomsonreuters::ema::access; 

int main(void) {
  Map map;
  for (int i = 0; i < 10000; ++i) { 
    FieldList fieldList;
    fieldList.complete();               
    map.addKeyInt(i, MapEntry::DeleteEnum, fieldList);
  }

  map.complete();
  return 0;
}

**Comment by bberner** [comment]
We have created a JIRA issue for this and are trying to reproduce. A fix will be in a future release.

**Comment by bberner** [comment]
Fixed with ESDK 1.2.1.L1 release.
