### ISSUE TITLE
EMAJ: ema.access.OmmDateTime vs upa.codec.DateTime

### ISSUE THREAD

**Issue by FrankConstructor** [thomsonreuters/Elektron-SDK#55]
The javadocs of some OmmDateTime interface methods hides those from the DateTime:
- millisecond()
ema: Returns Millisecond.
upa: The millisecond of the second (0 - 999 where 65535 indicates blank).
- microsecond()
ema: Returns Microsecond.
upa: The microsecond of the millisecond (0 - 999 where 2047 indicates blank).
- nanosecond()
ema: Returns Nanosecond.
upa: The nanosecond of the microsecond (0 - 999 where 2047 indicates blank).

ema.access.OmmDateTimeImpl forwards these methods directly to the upa.codec.DateTime(Impl).

Is my understanding correct, that the magic numbers of the upa "indicates blank" have to be checked when using the Omm methods?

**Comment by maydu** [comment]
Yes, EMA OMMDateTime interface such as millisecond()  which could return the number between 0 - 999  or blank magic number (65535 in this case). There are two ways to check if it is blank.
1>call code() function on OmmDateTime to see if it is DataCode.Blank. If answer is yes, it means client app will get blank data after decoding.
2>or call each function (such as microsecond())  and checking the magic number for blank.

Hope this can help.

**Comment by FrankConstructor** [comment]
These are semantics that are quite important. I suggest to extend the ema side's OmmDateTime and OmmTime javadoc accordingly.

**Comment by FrankConstructor** [comment]
You mention the `ommDateTime.code() == DataCode.Blank` situation.
My understanding is that in that case the whole object has no data.

In contrast, the individual _foo_second() methods return magic numbers for their specific attributes.

An example:
ommDateTime.code() != DataCode.Blank
ommDateTime.year() = 2018 -> can be used
ommDateTime.nanosecond() = 2047 -> cannot be used and needs to be managed by the using application.

**Comment by FrankConstructor** [comment]
Are these magic numbers somewhere declared - e.g. in an interface?

**Comment by maydu** [comment]
OMMDateTime is a read only interface, it returns year value, nansecond value... by decoding values from wire. For example, ommDateTime.code() = Blank, it means all date and time values are set to their respective blank value. If any individual member is set to a blank value, only that member is blank, code() returns DataCode.NO_CODE.

What is your use case?  But you can check for magic blank number on each date or time function call. 
Thanks for pointing out our document deficiency. Yes, we will add some enhancement on docs in the future releases.

For now, you can find all blank indicator/number on FieldEntry interface. 

 @param year added OmmDateTime year (0 - 4095 where 0 indicates  blank)
	 * @param month added OmmDateTime month (0 - 12 where 0 indicates blank)
	 * @param day added OmmDateTime day (0 - 31 where 0 indicates blank)
	 * @param hour added OmmDateTime hour (0 - 59 where 255 indicates blank)
	 * @param minute added OmmDateTime minute (0 - 59 where 255 indicates blank)
	 * @param second added OmmDateTime second (0 - 60 where 255 indicates blank)
	 * @param millisecond added OmmDateTime millisecond (0 - 999 where 65535 indicates blank)
	 * @param microsecond added OmmDateTime microsecond (0 - 999 where 2047 indicates blank)
	 * @param nanosecond added OmmDateTime nanosecond (0 - 999 where 2047 indicates blank)
	 *

**Comment by bberner** [comment]
Fixed with ESDK 1.2.1.L1 release.
