### ISSUE TITLE
EMAJ: ema.access.OmmDateTime to Calendar

### ISSUE THREAD

**Issue by FrankConstructor** [thomsonreuters/Elektron-SDK#56]
rfa.omm.OMMDateTime provided toCalendar and toDate methods.
ema.access.OmmDateTime lacks those.

The implementing rfa.internal.rwf.RwfDateTime class constructs an internal GregorianCalendar object with timezone = GMT and locale = UK.

If an application would like to convert the ema OmmDateTime to a Calendar, are these timezone/locale settings still applicable?
Are dates/times always relative to GMT in ema?

**Comment by maydu** [comment]
Hi Frank,
Do you still have questions on this stream? 

Thanks,
May

**Comment by FrankConstructor** [comment]
Yes, what do you mean exactly with "provider's documentation"?
I guess you refer to e.g. the specific source of a RIC.

**Comment by vlevendel** [comment]
@FrankConstructor any further questions on this issue? Or can this be closed?
