### ISSUE TITLE
Missing afxres.h when building in VS 2017

### ISSUE THREAD

**Issue by stevenuk** [thomsonreuters/Elektron-SDK#58]
I just tried a clean build as follows:
```
git clone https://github.com/thomsonreuters/Elektron-SDK Elektron-SDK
cmake -HElektron-SDK -BElektron-SDK_build -G "Visual Studio 15 2017 Win64"
msbuild Elektron-SDK_build\esdk.sln /p:Configuration=Debug_MDd;Platform=x64
```
However, I get error RC1015 due to missing afxres.h files when the build eventually reaches the following files:
* Eta\Include\rssl.rc
* Eta\Impl\EtaJni\Include\rsslEtaJNI.rc
* Eta\Include\rsslVA.rc
* Ema\Src\Access\Ema.rc

A work-around it to replace afxres.h with windows.h.

**Comment by bberner** [comment]
Thank you for your feedback. A JIRA issue has been created and the issue is being investigated. We’ll let you know if we have any problems reproducing the issue.

**Comment by bberner** [comment]
This is a known issue with VS 2017. See instructions for how to resolve in link below. Make sure "MFC and ATL support (x86 and x64)" and "C++/CLI support" are both selected when installing.

https://social.msdn.microsoft.com/Forums/en-US/6b69607a-8a84-4e46-b3c8-5cd832bfb9c7/vs-2017-rc-file-error-rc1015-cannot-open-include-file-afxresh?forum=vcgeneral

**Comment by stevenuk** [comment]
After installing the missing components and reverting the work-around changes to the RC files, my build completed successfully.  Thank you for finding the solution.

**Comment by bitsrules** [comment]
In the newest version of Visual Studio 2017 this seems to have been separated into two components that needs to be installed.
1. Visual C++ **ATL** for x86 and x64
2. Visual C++ **MFC** for x86 and x64
