### ISSUE TITLE
OracleLinux 6 support in EMA

### ISSUE THREAD

**Issue by sdeber** [thomsonreuters/Elektron-SDK#6]
EMA cannot be compiled on OracleLinux 6 series.  When running make under the folder 'Elektron-SDK/Cpp-C/Ema/Src/Access', it always fails with the message 'makefile:27: *** unsupported environment.  Stop.'. After looking into the makefile, it seems that EMA will only compile on OracleServer 7. Is this a bug or 6 series will not be supported any more?

**Comment by andrzejczop** [comment]
Hi,
The native build of the libema (e.g. compilation of files in the Src/Access directory) on the OracleLinux 6 has never been supported. However, one can run the EMA applications on the OracleLinux 6 provided the applications are linked against the libema built on the RedHat 6.

The ReadMe.md file lists the officially supported and qualified platforms.

Hope this helps.
