### ISSUE TITLE
EMAJ: StatusMsgImpl clear() not complete

### ISSUE THREAD

**Issue by FrankConstructor** [thomsonreuters/Elektron-SDK#64]
The StatusMsgImpl (com.thomsonreuters.ema.access) `clear()` method delegates to `MsgImpl.msgClear()`.
It does not reset it's internal variables `_state` and `_stateSet`.

Similarly, the RefreshMsgImpl does not reset `_state`, `_stateSet`, `_qos`, `_qosSet`.

Maven version is 3.2.0.1.

**Comment by bberner** [comment]
Thank you for your feedback. A JIRA issue has been created and the issue is being investigated. We'll let you know if we need further information.

**Comment by bberner** [comment]
This is the intended implementation. StatusMsg Javadoc states "Decoding of just encoded StatusMsg in the same application is not supported". Encoding in this context means altering the StatusMsg in any manner including calling the clear() method.

**Comment by FrankConstructor** [comment]
See my last comment in https://github.com/thomsonreuters/Elektron-SDK/issues/63
