### ISSUE TITLE
EMAJ OmmState.StatusCode vs StateCodes

### ISSUE THREAD

**Issue by FrankConstructor** [thomsonreuters/Elektron-SDK#65]
The status values in com.thomsonreuters.ema.access and com.thomsonreuters.upa.codec differ.

OmmState.StatusCode | . | StateCodes | .
---- | ---- | ---- | ----
NONE | 0 | NONE | 0
NOT_FOUND | 1 | NOT_FOUND | 1
TIMEOUT | 2 | TIMEOUT | 2
NOT_AUTHORIZED | 3 | NOT_ENTITLED | 3
INVALID_ARGUMENT | 4 | INVALID_ARGUMENT |   4
USAGE_ERROR | 5 | USAGE_ERROR | 5
PREEMPTED | 6 | PREEMPTED | 6
JUST_IN_TIME_CONFLATION_STARTED | 7 |   JIT_CONFLATION_STARTED | 7
TICK_BY_TICK_RESUMED | 8 |   REALTIME_RESUMED | 8
FAILOVER_STARTED | 9 | FAILOVER_STARTED |   9
FAILOVER_COMPLETED | 10 |   FAILOVER_COMPLETED | 10
GAP_DETECTED | 11 | GAP_DETECTED | 11
NO_RESOURCES | 12 | NO_RESOURCES | 12
TOO_MANY_ITEMS | 13 | TOO_MANY_ITEMS | 13
ALREADY_OPEN | 14 | ALREADY_OPEN | 14
SOURCE_UNKNOWN | 15 | SOURCE_UNKNOWN | 15
NOT_OPEN | 16 | NOT_OPEN | 16
(na) |  | RESERVED17 | 17
(na) |  | RESERVED18 | 18
NON_UPDATING_ITEM | 19 | NON_UPDATING_ITEM | 19
UNSUPPORTED_VIEW_TYPE | 20 | UNSUPPORTED_VIEW_TYPE | 20
INVALID_VIEW | 21 | INVALID_VIEW | 21
FULL_VIEW_PROVIDED | 22 | FULL_VIEW_PROVIDED | 22
UNABLE_TO_REQUEST_AS_BATCH | 23 | UNABLE_TO_REQUEST_AS_BATCH | 23
(na) |  | RESERVED24 | 24
(na) |  | RESERVED25 | 25
NO_BATCH_VIEW_SUPPORT_IN_REQ | 26 | NO_BATCH_VIEW_SUPPORT_IN_REQ | 26
EXCEEDED_MAX_MOUNTS_PER_USER | 27 | EXCEEDED_MAX_MOUNTS_PER_USER | 27
ERROR | 28 | ERROR | 28
DACS_DOWN | 29 | DACS_DOWN | 29
USER_UNKNOWN_TO_PERM_SYS | 30 | USER_UNKNOWN_TO_PERM_SYS | 30
DACS_MAX_LOGINS_REACHED | 31 | DACS_MAX_LOGINS_REACHED | 31
DACS_USER_ACCESS_TO_APP_DENIED | 32 | DACS_USER_ACCESS_TO_APP_DENIED | 32
(na) |  | GAP_FILL | 33
(na) |  | APP_AUTHORIZATION_FAILED | 35
INVALID_FORMED_MSG | 256 | (na)  | 
CHANNEL_UNAVAILABLE | 257 | (na) | 
SERVICE_UNAVAILABLE | 258 | (na) | 
SERVICE_DOWN | 259 | (na) | 
SERVICE_NOT_ACCEPTING_REQUESTS | 260 | (na) | 
LOGIN_CLOSED | 261 | (na) | 
DIRECTORY_CLOSED | 262 | (na) | 
ITEM_NOT_FOUND | 263 | (na) | 
DICTIONARY_UNAVAILABLE | 264 | (na) | 
FIELD_ID_NOT_FOUND_DICTIONARY_UNAVAILABLE | 265 | (na) | 
ITEM_REQUEST_TIMEOUT | 266 | (na) | 

On OmmState side it is understandable that the reserved values of StatusCodes are not available.
In contrast, the OmmState values 256-266 cannot be used in some state-setter methods because StateImpl (com.thomsonreuters.upa.codec) checks them against MAX_RESERVED = 127:
```
if (!(code >= StateCodes.NONE && code <= StateCodes.MAX_RESERVED)) {
   return CodecReturnCodes.INVALID_ARGUMENT;
}
```
For example RefreshMsgImpl  then throws:
> Exception Type='OmmInvalidUsageException', Text='Attempt to specify invalid state. Passed in value is='1 / 1 / 264 / 264'.

Is there any explanation why the 256-266 range cannot be used?

Btw: Is "FIELD_ID_NOT_FOUND__DICTIONARY_UNAVAILABLE_" really correct? Seems like a copy/paste error.

**Comment by soranat** [comment]
The status codes starting from 256 to 266 were intended to use only by EMA to generate its own StatusMsg when it faces any errors defined in the status codes to the registered clients.

However, the additional status codes defined by EMA have never been used so the codes will be removed in the next maintenance release to avoid confusion.

**Comment by FrankConstructor** [comment]
Ok, thank you for this information.
