### ISSUE TITLE
specifying consumer config host/port by function call does not work

### ISSUE THREAD

**Issue by johnnyfarraj** [thomsonreuters/Elektron-SDK#68]
I have an OmmConsumer app. it works fine when I specify the host/port in the emxConfig.xml file in the <Channel> section. But if I do it programmatically by calling config.host(), the connection times out. I debugged the call through OmmConsumerConfigImpl to EmaConfigImpl and I can see the values being set in _hostnameSetViaFunctionCall/_portSetViaFunctionCall. why are these treated differently?

**Comment by timvanepps-tr** [comment]
Both of these works for me:
(1).  OmmConsumerConfig config;
       OmmConsumer consumer( config.host("localhost:14002").username( "user" ) );
(2)   OmmConsumer consumer( OmmConsumerConfig().host("localhost:14002").username( "user" ) );

Perhaps I've misunderstood your question. Could you perhaps send us a few lines of code that illustrate the issue.

Thanks.

**Comment by johnnyfarraj** [comment]
I do call the methods just like above, but the result is not the same, my consumer does not initialize.

**Comment by timvanepps-tr** [comment]
try setting your LoggingSeverity to Verbose. Inside the configuration for your logger, use:

	<LoggerSeverity value="LoggerSeverity::Verbose"/>

Your logging output should now include an entry showing more details about the consumer connection attempt including the hostName and port. Maybe that information will provide a hint. Might be useful to compare the logging output between successful and non-successful connection attempts.

**Comment by johnnyfarraj** [comment]
ok I will produce more logging and compare. thanks

**Comment by vlevendel** [comment]
@johnnyfarraj Any update?

**Comment by johnnyfarraj** [comment]
the issue has been resolved.
