### ISSUE TITLE
ESDK is crashing

### ISSUE THREAD

**Issue by ETNV** [thomsonreuters/Elektron-SDK#75]
Hi there,

Using EMA ESDK 1.1.1 I started seeing crashes. The crash is happening within this chunk of code:

![image](https://user-images.githubusercontent.com/41647233/43158685-4afcaeb0-8f4e-11e8-99de-cb1aae133771.png)

And the stack trace of the crash is:
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./Equity_FeedSrv_33 --ini settings.ini'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007fc9ca804428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7fc98affd700 (LWP 67025))]
(gdb) bt
#0  0x00007fc9ca804428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007fc9ca80602a in __GI_abort () at abort.c:89
#2  0x00007fc9ca7fcbd7 in __assert_fail_base (fmt=<optimized out>, assertion=assertion@entry=0xb7aa00 "pWatchlistImpl->base.channelState == WL_CHS_LOGGED_IN", 
    file=file@entry=0xb7a8f0 "Reactor/Watchlist/rsslWatchlistImpl.c", line=line@entry=599, function=function@entry=0xb7b700 <__PRETTY_FUNCTION__.9541> "rsslWatchlistProcessTimer") at assert.c:92
#3  0x00007fc9ca7fcc82 in __GI___assert_fail (assertion=0xb7aa00 "pWatchlistImpl->base.channelState == WL_CHS_LOGGED_IN", file=0xb7a8f0 "Reactor/Watchlist/rsslWatchlistImpl.c", line=599, 
    function=0xb7b700 <__PRETTY_FUNCTION__.9541> "rsslWatchlistProcessTimer") at assert.c:101
#4  0x00000000009c7bd8 in rsslWatchlistProcessTimer (pWatchlist=0x7fc99003c1b0, currentTime=1532351287062, pErrorInfo=0x7fc990005100) at Reactor/Watchlist/rsslWatchlistImpl.c:599
#5  0x00000000009bd6e5 in _reactorDispatchEventFromQueue (pReactorImpl=0x7fc990011e50, pQueue=0x7fc990012de0, pError=0x7fc990005100) at Reactor/rsslReactor.c:2025
#6  0x00000000009baddc in rsslReactorDispatch (pReactor=0x7fc990011e50, pDispatchOpts=0x7fc98affce70, pError=0x7fc990005100) at Reactor/rsslReactor.c:923
#7  0x0000000000905513 in thomsonreuters::ema::access::OmmBaseImpl::rsslReactorDispatchLoop(long long, unsigned int, bool&) ()
#8  0x0000000000905a47 in thomsonreuters::ema::access::OmmBaseImpl::run() ()
#9  0x000000000082ee9a in thomsonreuters::ema::access::Thread::runThread(void*) ()
#10 0x00007fc9cbcf86ba in start_thread (arg=0x7fc98affd700) at pthread_create.c:333
#11 0x00007fc9ca8d63dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Did anyone see this before?

Thanks,

German

**Comment by bberner** [comment]
ESDK 1.1.1 is not the latest version of ESDK. Do you see the same problem with ESDK 1.2.0? Can you give details about how to reproduce the problem?

**Comment by ETNV** [comment]
Hi bberner,

After replacing for the latest version 1.2.0, it's not crashing anymore.

Thanks, German

**Comment by bberner** [comment]
Great, I'll close the issue then.
