### ISSUE TITLE
readme missing examples configuration details

### ISSUE THREAD

**Issue by PluRav** [thomsonreuters/Elektron-SDK#79]
Hello, I just cloned and tried running an example included in this repo (runconsumer100) It seems that I'm missing some configuration steps as there is nothing responding on localhost.

Can you please extend the readme file with section describing the missing configuration steps?
[log.txt](https://github.com/thomsonreuters/Elektron-SDK/files/2302225/log.txt)

**Comment by seba5** [comment]
Hi, thanks for the suggestion. 
You can run one of the sample training Interactive Providers examples along with the Consumer examples to get the Consumer application working. Thank you.

**Comment by PluRav** [comment]
Thanks, proposed solution was enough to get the examples running.
