### ISSUE TITLE
how to encode BLANK data with ema 

### ISSUE THREAD

**Issue by donghao-hao** [thomsonreuters/Elektron-SDK#84]
We are developing an application,  and want to encode FID value as BLANK, no matter what fid type is.
like encode FID22(REAL) as BLANK, or FID3851(TIME) as BLANK.
Can you give me an example of EMA functions to encoding this kind of FID entry

**Comment by seba5** [comment]
Sorry for a delayed response, it was a holiday yesterday in US. 
Below is the example of the BLANK encoding for the FIDs that you have asked. 

`fieldList.add( EmaFactory.createFieldEntry().codeReal(22));`
`fieldList.add( EmaFactory.createFieldEntry().codeTime(3851));`

For more examples of encoding of different data typed you can check our junit test code. 

[https://github.com/thomsonreuters/Elektron-SDK/blob/master/Java/Ema/Core/src/test/java/com/thomsonreuters/ema/unittest/FieldListTests.java](url)

**Comment by donghao-hao** [comment]
Thank you

**Comment by seba5** [comment]
I will close the issue. Thank you.
