### ISSUE TITLE
C++ SDK dependency: builds for non RHEL6_64_GCC444 or OL7_64_GCC482

### ISSUE THREAD

**Issue by linmaosong2018** [thomsonreuters/Elektron-SDK#86]
My build fails here:

```
[ 29%] Linking C executable ../../../../../../Cpp-C/Eta/Executables/UBU18_64_GCC730/Optimized/Shared/Provider
[ 30%] Built target Provider_shared
make[2]: *** No rule to make target 'Elektron-SDK-BinaryPack_dacs_LIBRARY-NOTFOUND', needed by '../Cpp-C/Eta/Executables/UBU18_64_GCC730/Optimized/authlock'.  Stop.
CMakeFiles/Makefile2:3183: recipe for target 'Cpp-C/Eta/Applications/Examples/AuthLock/CMakeFiles/authlock.dir/all' failed
make[1]: *** [Cpp-C/Eta/Applications/Examples/AuthLock/CMakeFiles/authlock.dir/all] Error 2
```

Grepping the problematic lib shows the build system is able to find the include files, not not the libraries:

```
grep -r -e'Elektron-SDK-BinaryPack_dacs' outdir
outdir/CMakeCache.txt:Elektron-SDK-BinaryPack_dacs_INCLUDE_DIRS:PATH=<prefix omitted>/Elektron-SDK-BinaryPack/Cpp-C/Eta/Utils/Dacs/Include
outdir/CMakeCache.txt:Elektron-SDK-BinaryPack_dacs_LIBRARY:FILEPATH=Elektron-SDK-BinaryPack_dacs_LIBRARY-NOTFOUND
```

With `export RCDEV_DEBUG_ENABLED=1`, this debug line appears to be related:

```
-- DEBUG message:
            Post Prefix Path:
                    RCDEV_POST_PREFIX_PATH   :   UBU18_64_GCC730/Optimized
```

However, there isn't such a path prefix for the Dacs lib:
```
$ ls Elektron-SDK-BinaryPack/Cpp-C/Eta/Utils/Dacs/Libs/
OL7_64_GCC482  RHEL6_64_GCC444
```

This appears to suggest only two distributions supported (Oracle Linux, RH6) , and each distribution must have a specific GCC version.

Is there a way around it? E.g. given my prefix (UBU18_64_GCC730), would it work with a sym link to one of the directories?

**Comment by DuncanSands** [comment]
Hi Linmao,

On 09/14/2018 01:04 PM, Linmao Song wrote:
> My build fails here:

we had much the same problem.  Our first solution was to link using the Redhat 
libraries, and this worked OK.  However with recent versions of the SDK you can 
build the libraries yourself (except for librsslVACache IIRC) so nowadays we 
don't bother with the binary pack (except for librsslVACache), we just build 
everything from source.  Rather than hacking the build system so it recognizes 
Ubuntu (needed for setting correct build flags IIRC) we made our own build 
system which integrates the Elektron build nicely into our overall build 
infrastructure.

Best wishes, Duncan.

**Comment by linmaosong2018** [comment]
> Hi Linmao,
> On 09/14/2018 01:04 PM, Linmao Song wrote: My build fails here:
> we had much the same problem. Our first solution was to link using the Redhat libraries, and this worked OK. However with recent versions of the SDK you can build the libraries yourself (except for librsslVACache IIRC) so nowadays we don't bother with the binary pack (except for librsslVACache), we just build everything from source. Rather than hacking the build system so it recognizes Ubuntu (needed for setting correct build flags IIRC) we made our own build system which integrates the Elektron build nicely into our overall build infrastructure. Best wishes, Duncan.
> […](#)

That's really good to know. I will try that. Many thanks for this helpful information, Duncan.

**Comment by linmaosong2018** [comment]
Indeed the symlink solution is fragile, just had a quick try:
```
[ 31%] Linking C executable ../../../../../../Cpp-C/Eta/Executables/UBU18_64_GCC730/Optimized/VAProvider
/usr/bin/x86_64-linux-gnu-ld: ../../../../../../Cpp-C/Eta/Libs/UBU18_64_GCC730/Optimized/librssl.a(numeric.c.o): undefined reference to symbol 'floor@@GLIBC_2.2.5'
/lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Cpp-C/Eta/Applications/Examples/VAProvider/CMakeFiles/VAProvider.dir/build.make:435: recipe for target '../Cpp-C/Eta/Executables/UBU18_64_GCC730/Optimized/VAProvider' failed
```

So it seems building the the binary pack is the way to go. Sorry for the silly question, but where can I find the source code for the binary pack? They don't appear to be among "thomsonreuters" repositories.

**Comment by DuncanSands** [comment]
Hi,

On 09/14/2018 02:36 PM, Linmao Song wrote:
> Indeed the symlink solution is fragile, just had a quick try:
> 
> |[ 31%] Linking C executable 
> ../../../../../../Cpp-C/Eta/Executables/UBU18_64_GCC730/Optimized/VAProvider 
> /usr/bin/x86_64-linux-gnu-ld: 
> ../../../../../../Cpp-C/Eta/Libs/UBU18_64_GCC730/Optimized/librssl.a(numeric.c.o): 
> undefined reference to symbol 'floor@@GLIBC_2.2.5' 
> /lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command 
> line collect2: error: ld returned 1 exit status 
> Cpp-C/Eta/Applications/Examples/VAProvider/CMakeFiles/VAProvider.dir/build.make:435: 
> recipe for target 
> '../Cpp-C/Eta/Executables/UBU18_64_GCC730/Optimized/VAProvider' failed |
> 
> So it seems building the the binary pack is the way to go. Sorry for the silly 
> question, but where can I find the source code for the binary pack? They don't 
> appear to be among "thomsonreuters" repositories.

all the source code is in the SDK itself.  You just need to work out how to 
persuade the build system to build the libraries!  We are using "Elektron SDK - 
C/C++ - 1.2.1 - Linux".

Best wishes, Duncan.

**Comment by seba5** [comment]
Hi, the binary pack is for the libraries that have not been opened source.

**Comment by seba5** [comment]
Hi, since there are no follow up questions we are closing this issue.

**Comment by Arrakis-10191** [comment]
> Hi,
> On 09/14/2018 02:36 PM, Linmao Song wrote: Indeed the symlink solution is fragile, just had a quick try: |[ 31%] Linking C executable ../../../../../../Cpp-C/Eta/Executables/UBU18_64_GCC730/Optimized/VAProvider /usr/bin/x86_64-linux-gnu-ld: ../../../../../../Cpp-C/Eta/Libs/UBU18_64_GCC730/Optimized/librssl.a(numeric.c.o): undefined reference to symbol 'floor@@GLIBC_2.2.5' /lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line collect2: error: ld returned 1 exit status Cpp-C/Eta/Applications/Examples/VAProvider/CMakeFiles/VAProvider.dir/build.make:435: recipe for target '../Cpp-C/Eta/Executables/UBU18_64_GCC730/Optimized/VAProvider' failed | So it seems building the the binary pack is the way to go. Sorry for the silly question, but where can I find the source code for the binary pack? They don't appear to be among "thomsonreuters" repositories.
> all the source code is in the SDK itself. You just need to work out how to persuade the build system to build the libraries! We are using "Elektron SDK - C/C++ - 1.2.1 - Linux". Best wishes, Duncan.

Hi Duncan, I'm having the same problem as linmaosong2018: using symlinks to point the linker to the Red Hat binary libraries gives the following error:
``
/usr/bin/ld: ../../../../../../Cpp-C/Eta/Libs/LIN19_64_GCC730/Optimized/librssl.a(numeric.c.o): undefined reference to symbol 'floor@@GLIBC_2.2.5'
/lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
``

Can you help with either what build flags to set to that the build system recognizes Ubuntu, or with how to persuade the build system to build the libraries.

Thanks a lot
