### ISSUE TITLE
how to serialize the  com.thomsonreuters.ema.access.Msg to Bytebuffer in Java EMA

### ISSUE THREAD

**Issue by donghao-hao** [thomsonreuters/Elektron-SDK#90]
We are trying to put refresh or update messages into other capsule, so we hope the encoded header and payload could be serialized into Byte buffer. Any suggestions please?

**Comment by soranat** [comment]
EMAJ provides the following method to get encoded RWF buffer from messages in the EMA's callback methods.

**public ByteBuffer asHex();**

For decoding the buffer, you have to use EMA decoding routine interfaces to get decoded data.

**Comment by donghao-hao** [comment]
Thank you very much @soranat

**Comment by schnappi17** [comment]
We had a encoded refreshMsg, but refreshMsg.asHex() returns a empty ByteBuffer of length 4096. 

Here is the test code we used:

`        if (msg instanceof RefreshMsg) {
          RefreshMsg r = (RefreshMsg) msg;
          ByteBuffer bb = r.asHex();
          provider.submit(r, r.streamId());
          ByteBuffer bbAfter = r.asHex();
          byte[] byteArray= new byte[bb.remaining()];
`

Where "bb" and "bbAfter" are both empty ByteBuffer. We saw the _rsslBuffer in msg is empty. Could you suggest on this?

**Comment by bberner** [comment]
EMA is not suited for this on the encode side. ETA is a better choice for easily accessing the encoded buffer.

**Comment by donghao-hao** [comment]
Thank you @bberner
