### ISSUE TITLE
Is there a way to description for enumerated fields ?

### ISSUE THREAD

**Issue by ajraja** [thomsonreuters/Elektron-SDK#91]
I'm using ETA C API in Linux. Is there a way to get a description of enumerated fields using the API ?

For example, the following lines were taken from enumtype.def file that came in the SDK. Is there a way to get the description in column 3 (MEANING) or something similar using the ETA API ?

!
! ACRONYM FID
! ------- ---
!
LOTSZUNITS 54
!
! VALUE DISPLAY MEANING
! ----- ------- -------
 0 " " Not allocated
 1 " AUD " Australian dollar
 2 " GBP " British pound
 3 "GBP/P" British pounds per point
 4 " CAD " Canadian dollar

**Comment by seba5** [comment]
Hi ajraja,

the information that contains the data from enumtype.def is store in the 

typedef struct {
	RsslEnum	value;		/*!< The actual value representing the type. */
	RsslBuffer	display;	/*!< A brief string representation describing what the type means(For example, this may be an abbreviation of a currency to be displayed to a user) */
	RsslBuffer	meaning;	/*!< A more elaborate description of what the value means. This information is typically optional and not displayed. */
} RsslEnumType; 

The meaning is in the meaning variable stored as RsslBuffer.

**Comment by ajraja** [comment]
First, I asked this question in TR developer portal and it seems to be not populated as per the response in the link below.

https://community.developers.thomsonreuters.com/questions/33590/is-there-a-way-to-description-for-enumerated-field.html?childToView=33602#answer-33602

Can you confirm if it is populated ?

Is there any other flag I need to set to have it populated ?

**Comment by MitchellKatoTR** [comment]
This is covered in the RDM usage guide.  From Chapter 5.6.2 of the RDM Usage Guide, the Meaning element is not required and typically not populated.

This will only be populated if the upstream provider is populating the value.  You will need to engage with TREP support or whomever is providing your data for this information.
