### ISSUE TITLE
Is there a way to know that the stream is fully closed?

### ISSUE THREAD

**Issue by zfarberov** [thomsonreuters/Elektron-SDK#92]
Hello,

This question is on behalf of a client, Etrade.

Is there  away to know with confidence, when a stream has been fully closed in ETA/UPA?

When consumer closes a stream in ETA, close request receipt is acknowledged by close ack.
However, there can sometimes be more updates, after close ack, but before close is fully completed.

rsslIsFinalMsg does not help, as it does not return true for an update
rsslIsFinalState does not provide the info

Thanks,
-Zoya

**Comment by vlevendel** [comment]
@zfarberov Thank you for your question. Receiving a close ack on a stream implies a close of that stream. There are additional questions about configuration of upstream components that API is connecting to. Please contact RDC for further investigation and support.
